<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PendleCodeMonkey.MC68000Emulator.Tests</RootNamespace>

    <IsPackable>false</IsPackable>

    <Authors>PendleCodeMonkey</Authors>

    <Nullable>enable</Nullable>
  </PropertyGroup>
	
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>	
	
  <ItemGroup>
    <Content Include="..\TestData\m68000\v1\ABCD.json" Link="TestData\ABCD.json" />
    <Content Include="..\TestData\m68000\v1\ADD.b.json" Link="TestData\ADD.b.json" />
    <Content Include="..\TestData\m68000\v1\ADD.l.json" Link="TestData\ADD.l.json" />
    <Content Include="..\TestData\m68000\v1\ADD.w.json" Link="TestData\ADD.w.json" />
    <Content Include="..\TestData\m68000\v1\ADDA.l.json" Link="TestData\ADDA.l.json" />
    <Content Include="..\TestData\m68000\v1\ADDA.w.json" Link="TestData\ADDA.w.json" />
    <Content Include="..\TestData\m68000\v1\ADDX.b.json" Link="TestData\ADDX.b.json" />
    <Content Include="..\TestData\m68000\v1\ADDX.l.json" Link="TestData\ADDX.l.json" />
    <Content Include="..\TestData\m68000\v1\ADDX.w.json" Link="TestData\ADDX.w.json" />
    <Content Include="..\TestData\m68000\v1\AND.b.json" Link="TestData\AND.b.json" />
    <Content Include="..\TestData\m68000\v1\AND.l.json" Link="TestData\AND.l.json" />
    <Content Include="..\TestData\m68000\v1\AND.w.json" Link="TestData\AND.w.json" />
    <Content Include="..\TestData\m68000\v1\ANDItoCCR.json" Link="TestData\ANDItoCCR.json" />
    <Content Include="..\TestData\m68000\v1\ANDItoSR.json" Link="TestData\ANDItoSR.json" />
    <Content Include="..\TestData\m68000\v1\ASL.b.json" Link="TestData\ASL.b.json" />
    <Content Include="..\TestData\m68000\v1\ASL.l.json" Link="TestData\ASL.l.json" />
    <Content Include="..\TestData\m68000\v1\ASL.w.json" Link="TestData\ASL.w.json" />
    <Content Include="..\TestData\m68000\v1\ASR.b.json" Link="TestData\ASR.b.json" />
    <Content Include="..\TestData\m68000\v1\ASR.l.json" Link="TestData\ASR.l.json" />
    <Content Include="..\TestData\m68000\v1\ASR.w.json" Link="TestData\ASR.w.json" />
    <Content Include="..\TestData\m68000\v1\Bcc.json" Link="TestData\Bcc.json" />
    <Content Include="..\TestData\m68000\v1\BCHG.json" Link="TestData\BCHG.json" />
    <Content Include="..\TestData\m68000\v1\BCLR.json" Link="TestData\BCLR.json" />
    <Content Include="..\TestData\m68000\v1\BSET.json" Link="TestData\BSET.json" />
    <Content Include="..\TestData\m68000\v1\BSR.json" Link="TestData\BSR.json" />
    <Content Include="..\TestData\m68000\v1\BTST.json" Link="TestData\BTST.json" />
    <Content Include="..\TestData\m68000\v1\CHK.json" Link="TestData\CHK.json" />
    <Content Include="..\TestData\m68000\v1\CLR.b.json" Link="TestData\CLR.b.json" />
    <Content Include="..\TestData\m68000\v1\CLR.l.json" Link="TestData\CLR.l.json" />
    <Content Include="..\TestData\m68000\v1\CLR.w.json" Link="TestData\CLR.w.json" />
    <Content Include="..\TestData\m68000\v1\CMP.b.json" Link="TestData\CMP.b.json" />
    <Content Include="..\TestData\m68000\v1\CMP.l.json" Link="TestData\CMP.l.json" />
    <Content Include="..\TestData\m68000\v1\CMP.w.json" Link="TestData\CMP.w.json" />
    <Content Include="..\TestData\m68000\v1\CMPA.l.json" Link="TestData\CMPA.l.json" />
    <Content Include="..\TestData\m68000\v1\CMPA.w.json" Link="TestData\CMPA.w.json" />
    <Content Include="..\TestData\m68000\v1\DBcc.json" Link="TestData\DBcc.json" />
    <Content Include="..\TestData\m68000\v1\DIVS.json" Link="TestData\DIVS.json" />
    <Content Include="..\TestData\m68000\v1\DIVU.json" Link="TestData\DIVU.json" />
    <Content Include="..\TestData\m68000\v1\EOR.b.json" Link="TestData\EOR.b.json" />
    <Content Include="..\TestData\m68000\v1\EOR.l.json" Link="TestData\EOR.l.json" />
    <Content Include="..\TestData\m68000\v1\EOR.w.json" Link="TestData\EOR.w.json" />
    <Content Include="..\TestData\m68000\v1\EORItoCCR.json" Link="TestData\EORItoCCR.json" />
    <Content Include="..\TestData\m68000\v1\EORItoSR.json" Link="TestData\EORItoSR.json" />
    <Content Include="..\TestData\m68000\v1\EXG.json" Link="TestData\EXG.json" />
    <Content Include="..\TestData\m68000\v1\EXT.l.json" Link="TestData\EXT.l.json" />
    <Content Include="..\TestData\m68000\v1\EXT.w.json" Link="TestData\EXT.w.json" />
    <Content Include="..\TestData\m68000\v1\ILLEGAL_LINEA.json" Link="TestData\ILLEGAL_LINEA.json" />
    <Content Include="..\TestData\m68000\v1\ILLEGAL_LINEF.json" Link="TestData\ILLEGAL_LINEF.json" />
    <Content Include="..\TestData\m68000\v1\JMP.json" Link="TestData\JMP.json" />
    <Content Include="..\TestData\m68000\v1\JSR.json" Link="TestData\JSR.json" />
    <Content Include="..\TestData\m68000\v1\LEA.json" Link="TestData\LEA.json" />
    <Content Include="..\TestData\m68000\v1\LINK.json" Link="TestData\LINK.json" />
    <Content Include="..\TestData\m68000\v1\LSL.b.json" Link="TestData\LSL.b.json" />
    <Content Include="..\TestData\m68000\v1\LSL.l.json" Link="TestData\LSL.l.json" />
    <Content Include="..\TestData\m68000\v1\LSL.w.json" Link="TestData\LSL.w.json" />
    <Content Include="..\TestData\m68000\v1\LSR.b.json" Link="TestData\LSR.b.json" />
    <Content Include="..\TestData\m68000\v1\LSR.l.json" Link="TestData\LSR.l.json" />
    <Content Include="..\TestData\m68000\v1\LSR.w.json" Link="TestData\LSR.w.json" />
    <Content Include="..\TestData\m68000\v1\MOVE.b.json" Link="TestData\MOVE.b.json" />
    <Content Include="..\TestData\m68000\v1\MOVE.l.json" Link="TestData\MOVE.l.json" />
    <Content Include="..\TestData\m68000\v1\MOVE.q.json" Link="TestData\MOVE.q.json" />
    <Content Include="..\TestData\m68000\v1\MOVE.w.json" Link="TestData\MOVE.w.json" />
    <Content Include="..\TestData\m68000\v1\MOVEA.l.json" Link="TestData\MOVEA.l.json" />
    <Content Include="..\TestData\m68000\v1\MOVEA.w.json" Link="TestData\MOVEA.w.json" />
    <Content Include="..\TestData\m68000\v1\MOVEfromSR.json" Link="TestData\MOVEfromSR.json" />
    <Content Include="..\TestData\m68000\v1\MOVEfromUSP.json" Link="TestData\MOVEfromUSP.json" />
    <Content Include="..\TestData\m68000\v1\MOVEM.l.json" Link="TestData\MOVEM.l.json" />
    <Content Include="..\TestData\m68000\v1\MOVEM.w.json" Link="TestData\MOVEM.w.json" />
    <Content Include="..\TestData\m68000\v1\MOVEP.l.json" Link="TestData\MOVEP.l.json" />
    <Content Include="..\TestData\m68000\v1\MOVEP.w.json" Link="TestData\MOVEP.w.json" />
    <Content Include="..\TestData\m68000\v1\MOVEtoCCR.json" Link="TestData\MOVEtoCCR.json" />
    <Content Include="..\TestData\m68000\v1\MOVEtoSR.json" Link="TestData\MOVEtoSR.json" />
    <Content Include="..\TestData\m68000\v1\MOVEtoUSP.json" Link="TestData\MOVEtoUSP.json" />
    <Content Include="..\TestData\m68000\v1\MULS.json" Link="TestData\MULS.json" />
    <Content Include="..\TestData\m68000\v1\MULU.json" Link="TestData\MULU.json" />
    <Content Include="..\TestData\m68000\v1\NBCD.json" Link="TestData\NBCD.json" />
    <Content Include="..\TestData\m68000\v1\NEG.b.json" Link="TestData\NEG.b.json" />
    <Content Include="..\TestData\m68000\v1\NEG.l.json" Link="TestData\NEG.l.json" />
    <Content Include="..\TestData\m68000\v1\NEG.w.json" Link="TestData\NEG.w.json" />
    <Content Include="..\TestData\m68000\v1\NEGX.b.json" Link="TestData\NEGX.b.json" />
    <Content Include="..\TestData\m68000\v1\NEGX.l.json" Link="TestData\NEGX.l.json" />
    <Content Include="..\TestData\m68000\v1\NEGX.w.json" Link="TestData\NEGX.w.json" />
    <Content Include="..\TestData\m68000\v1\NOP.json" Link="TestData\NOP.json" />
    <Content Include="..\TestData\m68000\v1\NOT.b.json" Link="TestData\NOT.b.json" />
    <Content Include="..\TestData\m68000\v1\NOT.l.json" Link="TestData\NOT.l.json" />
    <Content Include="..\TestData\m68000\v1\NOT.w.json" Link="TestData\NOT.w.json" />
    <Content Include="..\TestData\m68000\v1\OR.b.json" Link="TestData\OR.b.json" />
    <Content Include="..\TestData\m68000\v1\OR.l.json" Link="TestData\OR.l.json" />
    <Content Include="..\TestData\m68000\v1\OR.w.json" Link="TestData\OR.w.json" />
    <Content Include="..\TestData\m68000\v1\ORItoCCR.json" Link="TestData\ORItoCCR.json" />
    <Content Include="..\TestData\m68000\v1\ORItoSR.json" Link="TestData\ORItoSR.json" />
    <Content Include="..\TestData\m68000\v1\PEA.json" Link="TestData\PEA.json" />
    <Content Include="..\TestData\m68000\v1\RESET.json" Link="TestData\RESET.json" />
    <Content Include="..\TestData\m68000\v1\ROL.b.json" Link="TestData\ROL.b.json" />
    <Content Include="..\TestData\m68000\v1\ROL.l.json" Link="TestData\ROL.l.json" />
    <Content Include="..\TestData\m68000\v1\ROL.w.json" Link="TestData\ROL.w.json" />
    <Content Include="..\TestData\m68000\v1\ROR.b.json" Link="TestData\ROR.b.json" />
    <Content Include="..\TestData\m68000\v1\ROR.l.json" Link="TestData\ROR.l.json" />
    <Content Include="..\TestData\m68000\v1\ROR.w.json" Link="TestData\ROR.w.json" />
    <Content Include="..\TestData\m68000\v1\ROXL.b.json" Link="TestData\ROXL.b.json" />
    <Content Include="..\TestData\m68000\v1\ROXL.l.json" Link="TestData\ROXL.l.json" />
    <Content Include="..\TestData\m68000\v1\ROXL.w.json" Link="TestData\ROXL.w.json" />
    <Content Include="..\TestData\m68000\v1\ROXR.b.json" Link="TestData\ROXR.b.json" />
    <Content Include="..\TestData\m68000\v1\ROXR.l.json" Link="TestData\ROXR.l.json" />
    <Content Include="..\TestData\m68000\v1\ROXR.w.json" Link="TestData\ROXR.w.json" />
    <Content Include="..\TestData\m68000\v1\RTE.json" Link="TestData\RTE.json" />
    <Content Include="..\TestData\m68000\v1\RTR.json" Link="TestData\RTR.json" />
    <Content Include="..\TestData\m68000\v1\RTS.json" Link="TestData\RTS.json" />
    <Content Include="..\TestData\m68000\v1\SBCD.json" Link="TestData\SBCD.json" />
    <Content Include="..\TestData\m68000\v1\Scc.json" Link="TestData\Scc.json" />
    <Content Include="..\TestData\m68000\v1\STOP.json" Link="TestData\STOP.json" />
    <Content Include="..\TestData\m68000\v1\SUB.b.json" Link="TestData\SUB.b.json" />
    <Content Include="..\TestData\m68000\v1\SUB.l.json" Link="TestData\SUB.l.json" />
    <Content Include="..\TestData\m68000\v1\SUB.w.json" Link="TestData\SUB.w.json" />
    <Content Include="..\TestData\m68000\v1\SUBA.l.json" Link="TestData\SUBA.l.json" />
    <Content Include="..\TestData\m68000\v1\SUBA.w.json" Link="TestData\SUBA.w.json" />
    <Content Include="..\TestData\m68000\v1\SUBX.b.json" Link="TestData\SUBX.b.json" />
    <Content Include="..\TestData\m68000\v1\SUBX.l.json" Link="TestData\SUBX.l.json" />
    <Content Include="..\TestData\m68000\v1\SUBX.w.json" Link="TestData\SUBX.w.json" />
    <Content Include="..\TestData\m68000\v1\SWAP.json" Link="TestData\SWAP.json" />
    <Content Include="..\TestData\m68000\v1\TAS.json" Link="TestData\TAS.json" />
    <Content Include="..\TestData\m68000\v1\TRAP.json" Link="TestData\TRAP.json" />
    <Content Include="..\TestData\m68000\v1\TRAPV.json" Link="TestData\TRAPV.json" />
    <Content Include="..\TestData\m68000\v1\TST.b.json" Link="TestData\TST.b.json" />
    <Content Include="..\TestData\m68000\v1\TST.l.json" Link="TestData\TST.l.json" />
    <Content Include="..\TestData\m68000\v1\TST.w.json" Link="TestData\TST.w.json" />
    <Content Include="..\TestData\m68000\v1\UNLINK.json" Link="TestData\UNLINK.json" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="Stardust.Utilities" Version="0.9.5" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="3.2.2" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\68000EmulatorLib\68000EmulatorLib.csproj" />
  </ItemGroup>

	<ItemGroup>
		<None Update="program.h68">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="program.lis">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Resource Include="program.a68">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<Generator>a68.bat proc.a68</Generator>
		</Resource>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="DisassemblerTests.cs">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="TestData\" />
	</ItemGroup>

</Project>
