using System;
using System.Text.RegularExpressions;
using Xunit;

namespace PendleCodeMonkey.MC68000Emulator.Tests
{
    using DebugMachine = MC68000EmulatorLib.Machine.Disassembler.DisassemblerMachine;

    /// <summary>
    /// Helpers to clean up test cases generated by the vasm assembler.
    /// </summary>
    public static class Extensions
    {
        private static readonly Regex regex = new(@"\s+");

        public static string RemoveWhiteSpaces(this string str)
        {
            return regex.Replace(str, String.Empty);
        }

        public static string RemoveMutipleWhiteSpaces(this string str)
        {
            return regex.Replace(str, " ");
        }
    }

    /// <summary>
    /// Testing used the vasm assembler, v 1.9. to assemble the test cases
    /// and generate the binary used as input for the tests.
    /// 
    ///   vasm.exe -m68000 -Fsrec -exec -o temp.h68 -L temp.lis temp.a68 
    /// 
    /// vasm 1.9 (c) in 2002-2022 Volker Barthelmann
    /// vasm M68k/CPU32/ColdFire cpu backend 2.5 (c) 2002-2021 Frank Wille
    /// vasm motorola syntax module 3.15d (c) 2002-2022 Frank Wille
    /// vasm motorola srecord output module 1.1 (c) 2015 Joseph Zatarski
    /// </summary>
    public class DisassemblerTests
    {
        /// <summary>
        /// Create an instance of the <see cref="DisassemblerMachine"/> class and populate the registers
        /// with some preset values.
        /// </summary>
        /// <returns>A new instance of the <see cref="DisassemblerMachine"/> class.</returns>
        internal static DebugMachine CreateMachine()
        {
            var machine = new MC68000EmulatorLib.Machine();
            //var state = new CPUState
            //{
            //    USP = 0x2000,
            //    SSP = 0x3000,
            //    SR = 0,
            //    PC = 0x4000
            //};
            //machine.SetCPUState(state);
            return new DebugMachine(machine);
        }

        internal static uint ParseAddress(string address)
        {
            // First 8 characters (hex)
            address = address.RemoveWhiteSpaces();
            uint addr = uint.Parse(address, System.Globalization.NumberStyles.HexNumber);
            return addr;
        }

        internal static byte[] ParseBytes(string byteString)
        {
            byteString = byteString.RemoveWhiteSpaces();
            byte[] bytes = new byte[byteString.Length / 2];
            for (int i = 0; i < bytes.Length; i++)
            {
                string b = byteString[(i * 2)..(i * 2 + 2)];
                bytes[i] = byte.Parse(b, System.Globalization.NumberStyles.HexNumber);
            }
            return bytes;
        }

        /// <summary>
        /// The test cases below were extracted from listing (.lis) files produced by the 
        /// vasm assembler.
        /// 
        /// These test cases are not exhaustive nor do they provide complete coverage. Rather, 
        /// they were generated from some actual binaries, disassembled, and "round-tripped"
        /// back through the assembler to generated the expected results.  Several errors
        /// in the disassembler were uncovered this way as well as some errors in the
        /// underlying emulator.
        /// </summary>
        /// <param name="addressString">absolute address of the instruction</param>
        /// <param name="byteString">binary machine code to disassemble</param>
        /// <param name="op">opcode that should be generated by disassembler</param>
        /// <param name="ea">effective address that should be generated by disassembler</param>
        [Theory]
        [InlineData("00010000", "3E7C1800", "MOVEA.L", "#$1800,SP")]
        [InlineData("00010004", "7000", "MOVEQ.L", "#0,D0")]
        [InlineData("00010006", "21C01800", "MOVE.L", "D0,$00001800")]
        [InlineData("0001000A", "21C01804", "MOVE.L", "D0,$00001804")]
        [InlineData("0001000E", "21C01808", "MOVE.L", "D0,$00001808")]
        [InlineData("00010012", "7001", "MOVEQ.L", "#1,D0")]
        [InlineData("00010014", "21C0180C", "MOVE.L", "D0,$0000180c")]
        [InlineData("00010018", "103C0080", "MOVE.B", "#$0080,D0")]
        [InlineData("0001001C", "11C01810", "MOVE.B", "D0,$00001810")]
        [InlineData("00010020", "103C0040", "MOVE.B", "#$0040,D0")]
        [InlineData("00010024", "11C01811", "MOVE.B", "D0,$00001811")]
        [InlineData("00010028", "103C0020", "MOVE.B", "#$0020,D0")]
        [InlineData("0001002C", "11C01812", "MOVE.B", "D0,$00001812")]
        [InlineData("00010030", "103C0010", "MOVE.B", "#$0010,D0")]
        [InlineData("00010034", "11C01813", "MOVE.B", "D0,$00001813")]
        [InlineData("00010038", "103C0008", "MOVE.B", "#$0008,D0")]
        [InlineData("0001003C", "11C01814", "MOVE.B", "D0,$00001814")]
        [InlineData("00010040", "103C0004", "MOVE.B", "#$0004,D0")]
        [InlineData("00010044", "11C01815", "MOVE.B", "D0,$00001815")]
        [InlineData("00010048", "103C0002", "MOVE.B", "#$0002,D0")]
        [InlineData("0001004C", "11C01816", "MOVE.B", "D0,$00001816")]
        [InlineData("00010050", "103C0001", "MOVE.B", "#$0001,D0")]
        [InlineData("00010054", "11C01817", "MOVE.B", "D0,$00001817")]
        [InlineData("00010058", "4E550000", "LINK", "A5,#0")]
        [InlineData("0001005C", "20381800", "MOVE.L", "$00001800,D0")]
        [InlineData("00010060", "5280", "ADDQ.L", "#1,D0")]
        [InlineData("00010062", "21C01800", "MOVE.L", "D0,$00001800")]
        [InlineData("00038002", "2E40          ", "MOVEA.L", " D0, SP        ")]
        [InlineData("00038000", "B180          ", "EOR.L  ", " D0, D0        ")]
        [InlineData("00038004", "2E7C00010000  ", "MOVEA.L", " #$00010000,SP ")]
        [InlineData("0003800A", "027CDFFF      ", "ANDI   ", " #$dfff,SR     ")]
        [InlineData("0003800E", "2E40          ", "MOVEA.L", " D0, SP        ")]
        [InlineData("00038010", "2E7C00020000  ", "MOVEA.L", " #$00020000,SP ")]
        [InlineData("00038016", "207C00030002  ", "MOVEA.L", " #$00030002,A0 ")]
        [InlineData("0003801C", "183900E80000  ", "MOVE.B ", " $00e80000,D4  ")]
        [InlineData("00038022", "1C3900030002  ", "MOVE.B ", " $00030002,D6  ")]
        [InlineData("00038028", "670000E6      ", "BEQ    ", " $00038110     ")]
        [InlineData("0003802C", "207C00030003  ", "MOVEA.L", " #$00030003,A0 ")]
        [InlineData("00038032", "283900030001  ", "MOVE.L ", " $00030001,D4  ")]
        [InlineData("00038038", "1C3900030003  ", "MOVE.B ", " $00030003,D6  ")]
        [InlineData("0003803E", "670000D0      ", "BEQ    ", " $00038110     ")]
        [InlineData("00038042", "207C00030004  ", "MOVEA.L", " #$00030004,A0 ")]
        [InlineData("00038048", "4AFC          ", "ILLEGAL", "               ")]
        [InlineData("0003804A", "1C3900030004  ", "MOVE.B ", " $00030004,D6  ")]
        [InlineData("00038050", "670000BE      ", "BEQ    ", " $00038110     ")]
        [InlineData("00038054", "207C00030005  ", "MOVEA.L", " #$00030005,A0 ")]
        [InlineData("0003805A", "7C00          ", "MOVEQ.L", " #0,D6         ")]
        [InlineData("0003805C", "7A01          ", "MOVEQ.L", " #1,D5         ")]
        [InlineData("0003805E", "8BC6          ", "DIVS.W ", " D6, D5        ")]
        [InlineData("00038060", "1C3900030005  ", "MOVE.B ", " $00030005,D6  ")]
        [InlineData("00038066", "670000A8      ", "BEQ    ", " $00038110     ")]
        [InlineData("0003806A", "207C00030006  ", "MOVEA.L", " #$00030006,A0 ")]
        [InlineData("00038070", "3C3C0005      ", "MOVE.W ", " #$0005,D6     ")]
        [InlineData("00038074", "3A3C0006      ", "MOVE.W ", " #$0006,D5     ")]
        [InlineData("00038078", "4B86          ", "CHK.W  ", " D6, D5        ")]
        [InlineData("0003807A", "1C3900030006  ", "MOVE.B ", " $00030006,D6  ")]
        [InlineData("00038080", "6700008E      ", "BEQ    ", " $00038110     ")]
        [InlineData("00038084", "207C00030007  ", "MOVEA.L", " #$00030007,A0 ")]
        [InlineData("0003808A", "2C3C7FFFFFFF  ", "MOVE.L ", " #$7fffffff,D6 ")]
        [InlineData("00038090", "DC86          ", "ADD.L  ", " D6, D6        ")]
        [InlineData("00038092", "4E76          ", "TRAPV  ", "               ")]
        [InlineData("00038094", "1C3900030007  ", "MOVE.B ", " $00030007,D6  ")]
        [InlineData("0003809A", "6774          ", "BEQ    ", " $00038110     ")]
        [InlineData("0003809C", "6068          ", "BRA    ", " $00038106     ")]
        [InlineData("0003809E", "321F          ", "MOVE.W ", " (SP)+,D1      ")]
        [InlineData("000380A0", "241F          ", "MOVE.L ", " (SP)+,D2      ")]
        [InlineData("000380A2", "361F          ", "MOVE.W ", " (SP)+,D3      ")]
        [InlineData("000380A4", "1C3C0001      ", "MOVE.B ", " #$0001,D6     ")]
        [InlineData("000380A8", "13C600030002  ", "MOVE.B ", " D6,$00030002  ")]
        [InlineData("000380AE", "4E73          ", "RTE    ", "               ")]
        [InlineData("000380B0", "321F          ", "MOVE.W ", " (SP)+,D1      ")]
        [InlineData("000380B2", "241F          ", "MOVE.L ", " (SP)+,D2      ")]
        [InlineData("000380B4", "361F          ", "MOVE.W ", " (SP)+,D3      ")]
        [InlineData("000380B6", "1C3C0001      ", "MOVE.B ", " #$0001,D6     ")]
        [InlineData("000380BA", "13C600030003  ", "MOVE.B ", " D6,$00030003  ")]
        [InlineData("000380C0", "4E73          ", "RTE    ", "               ")]
        [InlineData("000380C2", "1C3C0001      ", "MOVE.B ", " #$0001,D6     ")]
        [InlineData("000380C6", "13C600030004  ", "MOVE.B ", " D6,$00030004  ")]
        [InlineData("000380CC", "4E73          ", "RTE    ", "               ")]
        [InlineData("000380CE", "1C3C0001      ", "MOVE.B ", " #$0001,D6     ")]
        [InlineData("000380D2", "13C600030005  ", "MOVE.B ", " D6,$00030005  ")]
        [InlineData("000380D8", "4E73          ", "RTE    ", "               ")]
        [InlineData("000380DA", "1C3C0001      ", "MOVE.B ", " #$0001,D6     ")]
        [InlineData("000380DE", "13C600030006  ", "MOVE.B ", " D6,$00030006  ")]
        [InlineData("000380E4", "4E73          ", "RTE    ", "               ")]
        [InlineData("000380E6", "1C3C0001      ", "MOVE.B ", " #$0001,D6     ")]
        [InlineData("000380EA", "13C600030007  ", "MOVE.B ", " D6,$00030007  ")]
        [InlineData("000380F0", "4E73          ", "RTE    ", "               ")]
        [InlineData("000380F2", "223C22222222  ", "MOVE.L ", " #$22222222,D1 ")]
        [InlineData("000380F8", "1C3C0001      ", "MOVE.B ", " #$0001,D6     ")]
        [InlineData("000380FC", "13C600030008  ", "MOVE.B ", " D6,$00030008  ")]
        [InlineData("00038102", "4E722000      ", "STOP   ", " #$2000        ")]
        [InlineData("00038106", "203C11111111  ", "MOVE.L ", " #$11111111,D0 ")]
        [InlineData("0003810C", "4E720000      ", "STOP   ", " #$0000        ")]
        [InlineData("00038110", "203CDEADBEEF  ", "MOVE.L ", " #$deadbeef,D0 ")]
        [InlineData("00038116", "4E722000      ", "STOP   ", " #$2000        ")]
        [InlineData("00401BE2", "3E7C2000        	", "MOVEA.L", "#$2000,SP            ")]
        [InlineData("00401BE6", "7E00            	", "MOVEQ.L", "#0,D7                ")]
        [InlineData("00401BE8", "7C00            	", "MOVEQ.L", "#0,D6                ")]
        [InlineData("00401BEA", "223C55AAAA55    	", "MOVE.L ", "#$55aaaa55,D1        ")]
        [InlineData("00401BF0", "203900F80000    	", "MOVE.L ", "$00f80000,D0         ")]
        [InlineData("00401BF6", "B081            	", "CMP.L  ", "D1,D0                ")]
        [InlineData("00401BF8", "660A            	", "BNE    ", "$00401c04            ")]
        [InlineData("00401BFA", "4CF9010100F80000	", "MOVEM.L", "$00f80000,D0/A0      ")]
        [InlineData("00401C02", "4ED0            	", "JMP    ", "(A0)                 ")]
        [InlineData("00401C04", "0887001B        	", "BCLR.L ", "#27,D7               ")]
        [InlineData("00401C08", "7200            	", "MOVEQ.L", "#0,D1                ")]
        [InlineData("00401C0A", "3E3C0006        	", "MOVE.W ", "#$0006,D7            ")]
        [InlineData("00401C0E", "43F900EFE1FE    	", "LEA    ", "$00efe1fe,A1         ")]
        [InlineData("00401C14", "137C00090600    	", "MOVE.B ", "#$0009,($0600,A1)    ")]
        [InlineData("00401C1A", "10291E00        	", "MOVE.B ", "($1e00,A1),D0        ")]
        [InlineData("00401C1E", "08C00003        	", "BSET.L ", "#3,D0                ")]
        [InlineData("00401C22", "13401E00        	", "MOVE.B ", "D0,($1e00, A1)       ")]
        [InlineData("00401C26", "08070018        	", "BTST.L ", "#24,D7               ")]
        [InlineData("00401C2A", "66000176        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401C2E", "45F900EFE1FE    	", "LEA    ", "$00efe1fe,A2         ")]
        [InlineData("00401C34", "102A1E00        	", "MOVE.B ", "($1e00,A2),D0        ")]
        [InlineData("00401C38", "08800000        	", "BCLR.L ", "#0,D0                ")]
        [InlineData("00401C3C", "15401E00        	", "MOVE.B ", "D0,($1e00, A2)       ")]
        [InlineData("00401C40", "102A1E00        	", "MOVE.B ", "($1e00,A2),D0        ")]
        [InlineData("00401C44", "08000001        	", "BTST.L ", "#1,D0                ")]
        [InlineData("00401C48", "6616            	", "BNE    ", "$00401c60            ")]
        [InlineData("00401C4A", "08C00000        	", "BSET.L ", "#0,D0                ")]
        [InlineData("00401C4E", "15401E00        	", "MOVE.B ", "D0,($1e00, A2)       ")]
        [InlineData("00401C52", "102A1E00        	", "MOVE.B ", "($1e00,A2),D0        ")]
        [InlineData("00401C56", "08000001        	", "BTST.L ", "#1,D0                ")]
        [InlineData("00401C5A", "6704            	", "BEQ    ", "$00401c60            ")]
        [InlineData("00401C5C", "08C7001A        	", "BSET.L ", "#26,D7               ")]
        [InlineData("00401C60", "3E3C0001        	", "MOVE.W ", "#$0001,D7            ")]
        [InlineData("00401C64", "4DFA0008        	", "LEA    ", "$00401c6e,A6         ")]
        [InlineData("00401C68", "60000A60        	", "JMP    ", "$004026ca            ")]
        [InlineData("00401C6C", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401C6E", "66000132        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401C72", "4247            	", "CLR.W  ", "D7                   ")]
        [InlineData("00401C74", "45F9005FF000    	", "LEA    ", "$005ff000,A2         ")]
        [InlineData("00401C7A", "102A0010        	", "MOVE.B ", "($0010,A2),D0        ")]
        [InlineData("00401C7E", "08070018        	", "BTST.L ", "#24,D7               ")]
        [InlineData("00401C82", "6600011E        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401C86", "45F900DFE1FF    	", "LEA    ", "$00dfe1ff,A2         ")]
        [InlineData("00401C8C", "4A2A1C00        	", "TST.B  ", "($1c00,A2)           ")]
        [InlineData("00401C90", "102A1A00        	", "MOVE.B ", "($1a00,A2),D0        ")]
        [InlineData("00401C94", "08070018        	", "BTST.L ", "#24,D7               ")]
        [InlineData("00401C98", "66000108        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401C9C", "3E3C000E        	", "MOVE.W ", "#$000e,D7            ")]
        [InlineData("00401CA0", "4DFA0008        	", "LEA    ", "$00401caa,A6         ")]
        [InlineData("00401CA4", "600009F0        	", "JMP    ", "$00402696            ")]
        [InlineData("00401CA8", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401CAA", "660000F6        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401CAE", "08070018        	", "BTST.L ", "#24,D7               ")]
        [InlineData("00401CB2", "660000EE        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401CB6", "3E3C0002        	", "MOVE.W ", "#$0002,D7            ")]
        [InlineData("00401CBA", "90C8            	", "SUBA   ", "A0,A0                ")]
        [InlineData("00401CBC", "43F80400        	", "LEA    ", "$00000400,A1         ")]
        [InlineData("00401CC0", "4DFA0008        	", "LEA    ", "$00401cca,A6         ")]
        [InlineData("00401CC4", "60000A2C        	", "JMP    ", "$004026f2            ")]
        [InlineData("00401CC8", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401CCA", "660000D6        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401CCE", "08070018        	", "BTST.L ", "#24,D7               ")]
        [InlineData("00401CD2", "660000CE        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401CD6", "4247            	", "CLR.W  ", "D7                   ")]
        [InlineData("00401CD8", "4DFA0008        	", "LEA    ", "$00401ce2,A6         ")]
        [InlineData("00401CDC", "6000091E        	", "JMP    ", "$004025fc            ")]
        [InlineData("00401CE0", "2E46            	", "MOVEA.L", "D6, SP               ")]
        [InlineData("00401CE2", "7C00            	", "MOVEQ.L", "#0,D6                ")]
        [InlineData("00401CE4", "3E3C0005        	", "MOVE.W ", "#$0005,D7            ")]
        [InlineData("00401CE8", "4DFA0008        	", "LEA    ", "$00401cf2,A6         ")]
        [InlineData("00401CEC", "60000C3C        	", "JMP    ", "$0040292a            ")]
        [InlineData("00401CF0", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401CF2", "660000AE        	", "BNE    ", "$00401da2            ")]
        [InlineData("00401CF6", "4247            	", "CLR.W  ", "D7                   ")]
        [InlineData("00401CF8", "0807001A        	", "BTST.L ", "#26,D7               ")]
        [InlineData("00401CFC", "661C            	", "BNE    ", "$00401d1a            ")]
        [InlineData("00401CFE", "2C4F            	", "MOVEA.L", "SP, A6               ")]
        [InlineData("00401D00", "3E7C0400        	", "MOVEA.L", "#$0400,SP            ")]
        [InlineData("00401D04", "41FAFCE4        	", "LEA    ", "$004019ea,A0         ")]
        [InlineData("00401D08", "92C9            	", "SUBA   ", "A1,A1                ")]
        [InlineData("00401D0A", "303C0040        	", "MOVE.W ", "#$0040,D0            ")]
        [InlineData("00401D0E", "5340            	", "SUBQ.W ", "#1,D0                ")]
        [InlineData("00401D10", "22D8            	", "MOVE.L ", "(A0)+,(A1)+          ")]
        [InlineData("00401D12", "51C8FFFC        	", "DBF.W  ", "D0,$00401d10         ")]
        [InlineData("00401D16", "6000E332        	", "JMP    ", "$0040004a            ")]
        [InlineData("00401D1A", "08C70010        	", "BSET.L ", "#16,D7               ")]
        [InlineData("00401D1E", "08C70016        	", "BSET.L ", "#22,D7               ")]
        [InlineData("00401D22", "4A47            	", "TST.W  ", "D7                   ")]
        [InlineData("00401D24", "6606            	", "BNE    ", "$00401d2c            ")]
        [InlineData("00401D26", "2C3C87654321    	", "MOVE.L ", "#$87654321,D6        ")]
        [InlineData("00401D2C", "383C000C        	", "MOVE.W ", "#$000c,D4            ")]
        [InlineData("00401D30", "4844            	", "SWAP   ", "D4                   ")]
        [InlineData("00401D32", "4DFA0008        	", "LEA    ", "$00401d3c,A6         ")]
        [InlineData("00401D36", "60000776        	", "JMP    ", "$004024ae            ")]
        [InlineData("00401D3A", "60000202        	", "JMP    ", "$00401f3e            ")]
        [InlineData("00401D3E", "48E7FFFE        	", "MOVEM.L", "D0-A6,-(SP)          ")]
        [InlineData("00401D42", "40E7            	", "MOVE   ", "SR,-(SP)             ")]
        [InlineData("00401D44", "7E00            	", "MOVEQ.L", "#0,D7                ")]
        [InlineData("00401D46", "46FC2700        	", "MOVE   ", "#$2700,SR            ")]
        [InlineData("00401D4A", "200E            	", "MOVE.L ", "A6,D0                ")]
        [InlineData("00401D4C", "45F900080000    	", "LEA    ", "$00080000,A2         ")]
        [InlineData("00401D52", "0C8000100000    	", "CMPI.L ", "#$00100000,D0        ")]
        [InlineData("00401D58", "6F06            	", "BLE    ", "$00401d60            ")]
        [InlineData("00401D5A", "45F900200000    	", "LEA    ", "$00200000,A2         ")]
        [InlineData("00401D60", "B2C8            	", "CMPA   ", "A0,A1                ")]
        [InlineData("00401D62", "6F36            	", "BLE    ", "$00401d9a            ")]
        [InlineData("00401D64", "7C00            	", "MOVEQ.L", "#0,D6                ")]
        [InlineData("00401D66", "3E3C0003        	", "MOVE.W ", "#$0003,D7            ")]
        [InlineData("00401D6A", "B4C9            	", "CMPA   ", "A1,A2                ")]
        [InlineData("00401D6C", "6C20            	", "BGE    ", "$00401d8e            ")]
        [InlineData("00401D6E", "B4C8            	", "CMPA   ", "A0,A2                ")]
        [InlineData("00401D70", "6F18            	", "BLE    ", "$00401d8a            ")]
        [InlineData("00401D72", "48E700E0        	", "MOVEM.L", "A0-A2,-(SP)          ")]
        [InlineData("00401D76", "224A            	", "MOVEA.L", "A2, A1               ")]
        [InlineData("00401D78", "4DFA0008        	", "LEA    ", "$00401d82,A6         ")]
        [InlineData("00401D7C", "60000974        	", "JMP    ", "$004026f2            ")]
        [InlineData("00401D80", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401D82", "661E            	", "BNE    ", "$00401da2            ")]
        [InlineData("00401D84", "4CDF0700        	", "MOVEM.L", "(SP)+,A0-A2          ")]
        [InlineData("00401D88", "204A            	", "MOVEA.L", "A2, A0               ")]
        [InlineData("00401D8A", "3E3C0004        	", "MOVE.W ", "#$0004,D7            ")]
        [InlineData("00401D8E", "4DFA0008        	", "LEA    ", "$00401d98,A6         ")]
        [InlineData("00401D92", "6000095E        	", "JMP    ", "$004026f2            ")]
        [InlineData("00401D96", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401D98", "6608            	", "BNE    ", "$00401da2            ")]
        [InlineData("00401D9A", "46DF            	", "MOVE   ", "(SP)+,SR             ")]
        [InlineData("00401D9C", "4CDF7FFF        	", "MOVEM.L", "(SP)+,D0-A6          ")]
        [InlineData("00401DA0", "4E75            	", "RTS    ", "                    ")]
        [InlineData("00401DA2", "0807001A        	", "BTST.L ", "#26,D7               ")]
        [InlineData("00401DA6", "6604            	", "BNE    ", "$00401dac            ")]
        [InlineData("00401DA8", "6000F2EA        	", "JMP    ", "$00401094            ")]
        [InlineData("00401DAC", "60000190        	", "JMP    ", "$00401f3e            ")]
        [InlineData("00401DB0", "48E7FFFE        	", "MOVEM.L", "D0-A6,-(SP)          ")]
        [InlineData("00401DB4", "40E7            	", "MOVE   ", "SR,-(SP)             ")]
        [InlineData("00401DB6", "46FC2700        	", "MOVE   ", "#$2700,SR            ")]
        [InlineData("00401DBA", "4A40            	", "TST.W  ", "D0                   ")]
        [InlineData("00401DBC", "6726            	", "BEQ    ", "$00401de4            ")]
        [InlineData("00401DBE", "5340            	", "SUBQ.W ", "#1,D0                ")]
        [InlineData("00401DC0", "6700016A        	", "BEQ    ", "$00401f2c            ")]
        [InlineData("00401DC4", "5340            	", "SUBQ.W ", "#1,D0                ")]
        [InlineData("00401DC6", "6700016C        	", "BEQ    ", "$00401f34            ")]
        [InlineData("00401DCA", "5340            	", "SUBQ.W ", "#1,D0                ")]
        [InlineData("00401DCC", "6700016A        	", "BEQ    ", "$00401f38            ")]
        [InlineData("00401DD0", "5340            	", "SUBQ.W ", "#1,D0                ")]
        [InlineData("00401DD2", "671C            	", "BEQ    ", "$00401df0            ")]
        [InlineData("00401DD4", "5340            	", "SUBQ.W ", "#1,D0                ")]
        [InlineData("00401DD6", "6770            	", "BEQ    ", "$00401e48            ")]
        [InlineData("00401DD8", "5340            	", "SUBQ.W ", "#1,D0                ")]
        [InlineData("00401DDA", "6778            	", "BEQ    ", "$00401e54            ")]
        [InlineData("00401DDC", "6000014E        	", "BRA    ", "$00401f2c            ")]
        [InlineData("00401DE0", "7C00            	", "MOVEQ.L", "#0,D6                ")]
        [InlineData("00401DE2", "2E10            	", "MOVE.L ", "(A0),D7              ")]
        [InlineData("00401DE4", "22680008        	", "MOVEA.L", "($0008,A0),A1        ")]
        [InlineData("00401DE8", "20680004        	", "MOVEA.L", "($0004,A0),A0        ")]
        [InlineData("00401DEC", "3207            	", "MOVE.W ", "D7, D1               ")]
        [InlineData("00401DEE", "E049            	", "LSR.W  ", "#8,D1                ")]
        [InlineData("00401DF0", "B27A0BB2        	", "CMP.W  ", "$004029a4,D1         ")]
        [InlineData("00401DF4", "6C000136        	", "BGE    ", "$00401f2c            ")]
        [InlineData("00401DF8", "E541            	", "ASL.W  ", "#2,D1                ")]
        [InlineData("00401DFA", "4BFA0BAA        	", "LEA    ", "$004029a6,A5         ")]
        [InlineData("00401DFE", "32351000        	", "MOVE.W ", "(0,A5,D1.W),D1       ")]
        [InlineData("00401E02", "4BF51000        	", "LEA    ", "(0,A5,D1.W),A5       ")]
        [InlineData("00401E06", "4DFA000A        	", "LEA    ", "$00401e12,A6         ")]
        [InlineData("00401E0A", "4ED5            	", "JMP    ", "(A5)                 ")]
        [InlineData("00401E0C", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401E0E", "6716            	", "BEQ    ", "$00401e26            ")]
        [InlineData("00401E10", "0807001D        	", "BTST.L ", "#29,D7               ")]
        [InlineData("00401E14", "670A            	", "BEQ    ", "$00401e20            ")]
        [InlineData("00401E16", "4DFA0004        	", "LEA    ", "$00401e1c,A6         ")]
        [InlineData("00401E1A", "4ED5            	", "JMP    ", "(A5)                 ")]
        [InlineData("00401E1C", "0807001C        	", "BTST.L ", "#28,D7               ")]
        [InlineData("00401E20", "6608            	", "BNE    ", "$00401e2a            ")]
        [InlineData("00401E22", "5307            	", "SUBQ.B ", "#1,D7                ")]
        [InlineData("00401E24", "66E4            	", "BNE    ", "$00401e0a            ")]
        [InlineData("00401E26", "0807001E        	", "BTST.L ", "#30,D7               ")]
        [InlineData("00401E2A", "670C            	", "BEQ    ", "$00401e38            ")]
        [InlineData("00401E2C", "4DFA000C        	", "LEA    ", "$00401e3a,A6         ")]
        [InlineData("00401E30", "600006CE        	", "JMP    ", "$00402500            ")]
        [InlineData("00401E34", "0807001F        	", "BTST.L ", "#31,D7               ")]
        [InlineData("00401E38", "670000F2        	", "BEQ    ", "$00401f2c            ")]
        [InlineData("00401E3C", "4E70            	", "RESET  ", "                    ")]
        [InlineData("00401E3E", "20780004        	", "MOVEA.L", "$00000004,A0         ")]
        [InlineData("00401E42", "4ED0            	", "JMP    ", "(A0)                 ")]
        [InlineData("00401E44", "7C00            	", "MOVEQ.L", "#0,D6                ")]
        [InlineData("00401E46", "2E10            	", "MOVE.L ", "(A0),D7              ")]
        [InlineData("00401E48", "22680008        	", "MOVEA.L", "($0008,A0),A1        ")]
        [InlineData("00401E4C", "20680004        	", "MOVEA.L", "($0004,A0),A0        ")]
        [InlineData("00401E50", "08070008        	", "BTST.L ", "#8,D7                ")]
        [InlineData("00401E54", "6714            	", "BEQ    ", "$00401e6a            ")]
        [InlineData("00401E56", "7200            	", "MOVEQ.L", "#0,D1                ")]
        [InlineData("00401E58", "4DFA000C        	", "LEA    ", "$00401e66,A6         ")]
        [InlineData("00401E5C", "60000098        	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401E60", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401E62", "660000A2        	", "BNE    ", "$00401f06            ")]
        [InlineData("00401E66", "08070009        	", "BTST.L ", "#9,D7                ")]
        [InlineData("00401E6A", "6712            	", "BEQ    ", "$00401e7e            ")]
        [InlineData("00401E6C", "7201            	", "MOVEQ.L", "#1,D1                ")]
        [InlineData("00401E6E", "4DFA000A        	", "LEA    ", "$00401e7a,A6         ")]
        [InlineData("00401E72", "60000082        	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401E76", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401E78", "6600008C        	", "BNE    ", "$00401f06            ")]
        [InlineData("00401E7C", "0807000A        	", "BTST.L ", "#10,D7               ")]
        [InlineData("00401E80", "6710            	", "BEQ    ", "$00401e92            ")]
        [InlineData("00401E82", "7202            	", "MOVEQ.L", "#2,D1                ")]
        [InlineData("00401E84", "4DFA0008        	", "LEA    ", "$00401e8e,A6         ")]
        [InlineData("00401E88", "606C            	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401E8A", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401E8C", "6678            	", "BNE    ", "$00401f06            ")]
        [InlineData("00401E8E", "0807000B        	", "BTST.L ", "#11,D7               ")]
        [InlineData("00401E92", "6712            	", "BEQ    ", "$00401ea6            ")]
        [InlineData("00401E94", "7203            	", "MOVEQ.L", "#3,D1                ")]
        [InlineData("00401E96", "4DFA000A        	", "LEA    ", "$00401ea2,A6         ")]
        [InlineData("00401E9A", "605A            	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401E9C", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401E9E", "6666            	", "BNE    ", "$00401f06            ")]
        [InlineData("00401EA0", "0807000C        	", "BTST.L ", "#12,D7               ")]
        [InlineData("00401EA4", "6714            	", "BEQ    ", "$00401eba            ")]
        [InlineData("00401EA6", "7204            	", "MOVEQ.L", "#4,D1                ")]
        [InlineData("00401EA8", "4DFA000C        	", "LEA    ", "$00401eb6,A6         ")]
        [InlineData("00401EAC", "6048            	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401EAE", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401EB0", "6654            	", "BNE    ", "$00401f06            ")]
        [InlineData("00401EB2", "0807000D        	", "BTST.L ", "#13,D7               ")]
        [InlineData("00401EB6", "6716            	", "BEQ    ", "$00401ece            ")]
        [InlineData("00401EB8", "7205            	", "MOVEQ.L", "#5,D1                ")]
        [InlineData("00401EBA", "4DFA000E        	", "LEA    ", "$00401eca,A6         ")]
        [InlineData("00401EBE", "6036            	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401EC0", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401EC2", "6642            	", "BNE    ", "$00401f06            ")]
        [InlineData("00401EC4", "0807000E        	", "BTST.L ", "#14,D7               ")]
        [InlineData("00401EC8", "6718            	", "BEQ    ", "$00401ee2            ")]
        [InlineData("00401ECA", "7206            	", "MOVEQ.L", "#6,D1                ")]
        [InlineData("00401ECC", "4DFA0010        	", "LEA    ", "$00401ede,A6         ")]
        [InlineData("00401ED0", "6024            	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401ED2", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401ED4", "6630            	", "BNE    ", "$00401f06            ")]
        [InlineData("00401ED6", "0807000F        	", "BTST.L ", "#15,D7               ")]
        [InlineData("00401EDA", "673E            	", "BEQ    ", "$00401f1a            ")]
        [InlineData("00401EDC", "7207            	", "MOVEQ.L", "#7,D1                ")]
        [InlineData("00401EDE", "4DFA0012        	", "LEA    ", "$00401ef2,A6         ")]
        [InlineData("00401EE2", "6012            	", "BRA    ", "$00401ef6            ")]
        [InlineData("00401EE4", "4A86            	", "TST.L  ", "D6                   ")]
        [InlineData("00401EE6", "661E            	", "BNE    ", "$00401f06            ")]
        [InlineData("00401EE8", "6030            	", "BRA    ", "$00401f1a            ")]
        [InlineData("00401EEA", "E341            	", "ASL.W  ", "#1,D1                ")]
        [InlineData("00401EEC", "4BFA0AB8        	", "LEA    ", "$004029a6,A5         ")]
        [InlineData("00401EF0", "32351000        	", "MOVE.W ", "(0,A5,D1.W),D1       ")]
        [InlineData("00401EF4", "4BF51000        	", "LEA    ", "(0,A5,D1.W),A5       ")]
        [InlineData("00401EF8", "4ED5            	", "JMP    ", "(A5)                 ")]
        [InlineData("00401EFA", "0807001D        	", "BTST.L ", "#29,D7               ")]
        [InlineData("00401EFE", "6712            	", "BEQ    ", "$00401f12            ")]
        [InlineData("00401F00", "4DFA000C        	", "LEA    ", "$00401f0e,A6         ")]
        [InlineData("00401F04", "4ED5            	", "JMP    ", "(A5)                 ")]
        [InlineData("00401F06", "0807001C        	", "BTST.L ", "#28,D7               ")]
        [InlineData("00401F0A", "6600FF1E        	", "BNE    ", "$00401e2a            ")]
        [InlineData("00401F0E", "5307            	", "SUBQ.B ", "#1,D7                ")]
        [InlineData("00401F10", "6600FF42        	", "BNE    ", "$00401e54            ")]
        [InlineData("00401F14", "0887000F        	", "BCLR.L ", "#15,D7               ")]
        [InlineData("00401F18", "6600FF3A        	", "BNE    ", "$00401e54            ")]
        [InlineData("00401F1C", "6000FF0C        	", "BRA    ", "$00401e2a            ")]
        [InlineData("00401F20", "46DF            	", "MOVE   ", "(SP)+,SR             ")]
        [InlineData("00401F22", "4CDF7FFF        	", "MOVEM.L", "(SP)+,D0-A6          ")]
        [InlineData("00401F26", "4E75            	", "RTS    ", "                    ")]
        [InlineData("00401F28", "301F            	", "MOVE.W ", "(SP)+,D0             ")]
        [InlineData("00401F2A", "6002            	", "BRA    ", "$00401f2e            ")]
        [InlineData("00401F2C", "7C00            	", "MOVEQ.L", "#0,D6                ")]
        [InlineData("00401F2E", "7E00            	", "MOVEQ.L ", "#0,D7                ")]
        [InlineData("00401F30", "46FC2700        	", "MOVE   ", "#$2700,SR            ")]
        [InlineData("00401F34", "7A00            	", "MOVEQ.L", "#0,D5                ")]
        [InlineData("00401F36", "4DFA0014        	", "LEA    ", "$00401f4c,A6         ")]
        [InlineData("00401F3A", "60000516        	", "JMP    ", "$00402452            ")]
        [InlineData("00401F3E", "4DFA0014        	", "LEA    ", "$00401f54,A6         ")]
        [InlineData("00401F42", "600003AA        	", "JMP    ", "$004022ee            ")]
        [InlineData("00401F46", "4A45            	", "TST.W  ", "D5                   ")]
        [InlineData("00401F48", "6B00031A        	", "BMI    ", "$00402264            ")]
        [InlineData("00401F4C", "0205007F        	", "ANDI.B ", "#$7f,D5              ")]
        [InlineData("00401F50", "0C05002A        	", "CMPI.B ", "#$2a,D5              ")]
        [InlineData("00401F54", "6614            	", "BNE    ", "$00401f6a            ")]
        [InlineData("00401F56", "08C70013        	", "BSET.L ", "#19,D7               ")]
        [InlineData("00401F5A", "60000308        	", "BRA    ", "$00402264            ")]
        [InlineData("00401F5E", "08070013        	", "BTST.L ", "#19,D7               ")]
        [InlineData("00401F62", "670002C8        	", "BEQ    ", "$0040222c            ")]
        [InlineData("00401F66", "08870013        	", "BCLR.L ", "#19,D7               ")]
        [InlineData("00401F6A", "0C050053        	", "CMPI.B ", "#$53,D5              ")]
        [InlineData("00401F6E", "6618            	", "BNE    ", "$00401f88            ")]
        [InlineData("00401F70", "08870010        	", "BCLR.L ", "#16,D7               ")]
        [InlineData("00401F74", "08870016        	", "BCLR.L ", "#22,D7               ")]
        [InlineData("00401F78", "600002BE        	", "BRA    ", "$00402238            ")]
        [InlineData("00401F7C", "0C05004C        	", "CMPI.B ", "#$4c,D5              ")]
        [InlineData("00401F80", "6630            	", "BNE    ", "$00401fb2            ")]
        [InlineData("00401F82", "7404            	", "MOVEQ.L", "#4,D2                ")]
        [InlineData("00401F84", "4DFA0014        	", "LEA    ", "$00401f9a,A6         ")]
        [InlineData("00401F88", "600003F2        	", "JMP    ", "$0040237c            ")]
        [InlineData("00401F8C", "2841            	", "MOVEA.L", "D1, A4               ")]
        [InlineData("00401F8E", "08070015        	", "BTST.L ", "#21,D7               ")]
        [InlineData("00401F92", "670002A4        	", "BEQ    ", "$00402238            ")]
        [InlineData("00401F96", "08870017        	", "BCLR.L ", "#23,D7               ")]
        [InlineData("00401F9A", "2001            	", "MOVE.L ", "D1, D0               ")]
        [InlineData("00401F9C", "7404            	", "MOVEQ.L", "#4,D2                ")]
        [InlineData("00401F9E", "4DFA029A        	", "LEA    ", "$0040223a,A6         ")]
        [InlineData("00401FA2", "60000412        	", "JMP    ", "$004023b6            ")]
        [InlineData("00401FA6", "0C050042        	", "CMPI.B ", "#$42,D5              ")]
        [InlineData("00401FAA", "6630            	", "BNE    ", "$00401fdc            ")]
        [InlineData("00401FAC", "7402            	", "MOVEQ.L", "#2,D2                ")]
        [InlineData("00401FAE", "4DFA0014        	", "LEA    ", "$00401fc4,A6         ")]
        [InlineData("00401FB2", "600003C8        	", "JMP    ", "$0040237c            ")]
        [InlineData("00401FB6", "3801            	", "MOVE.W ", "D1, D4               ")]
        [InlineData("00401FB8", "08070015        	", "BTST.L ", "#21,D7               ")]
        [InlineData("00401FBC", "6700027A        	", "BEQ    ", "$00402238            ")]
        [InlineData("00401FC0", "08870017        	", "BCLR.L ", "#23,D7               ")]
        [InlineData("00401FC4", "2001            	", "MOVE.L ", "D1, D0               ")]
        [InlineData("00401FC6", "7402            	", "MOVEQ.L", "#2,D2                ")]
        [InlineData("00401FC8", "4DFA0270        	", "LEA    ", "$0040223a,A6         ")]
        [InlineData("00401FCC", "600003E8        	", "JMP    ", "$004023b6            ")]
        [InlineData("00401FD0", "0C050044        	", "CMPI.B ", "#$44,D5              ")]
        public void TestDisassembly(string addressString, string byteString, string op, string ea)
        {
            DebugMachine machine = CreateMachine();

            uint address = ParseAddress(addressString);
            byte[] bytes = ParseBytes(byteString);
            machine.LoadExecutableData(bytes, address, true);

            MC68000EmulatorLib.Machine.Disassembler disassembler = new(machine);
            var list = disassembler.Disassemble(address, (uint)bytes.Length);

            Assert.Single(list);
            var record = list[0];

            string assembly = record.Assembly.RemoveMutipleWhiteSpaces();

            string[] disassembly = assembly.Split(' ');
            Assert.True(disassembly.Length == 1 || disassembly.Length == 2);
            string cleanOp = op.RemoveWhiteSpaces();
            string cleanEa = ea.RemoveWhiteSpaces();
            string cleand0 = disassembly[0].RemoveWhiteSpaces();
            if (cleanOp == "JMP" && cleand0 == "BRA")
            {
                cleanOp = "BRA";
            }
            Assert.Equal(cleanOp, cleand0);
            if (cleanEa.Length > 0)
            {
                string cleand1 = disassembly[1].RemoveWhiteSpaces();
                Assert.Equal(cleanEa, cleand1);
            }
        }
    }
}
