<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <LangVersion>preview</LangVersion>
	  <RootNamespace>PendleCodeMonkey.MC68000EmulatorLib</RootNamespace>
    <Authors>PendleCodeMonkey</Authors>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <Deterministic>False</Deterministic>
	  <Optimize>True</Optimize>
	  <PublishAot>true</PublishAot>
	  <NativeLib>Shared</NativeLib>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stardust.Utilities" Version="0.9.8" />
  </ItemGroup>

</Project>
