// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.ABCD_SBCD(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.AppendSizeAndTab(PendleCodeMonkey.MC68000EmulatorLib.Enumerations.OpSize,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.AppendSizeAndTab(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.CMPM(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.EXG(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.EXT(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.HasSourceExtWord1(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.IMMEDtoSR(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.LINK(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.MOVEP(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.MOVEQ(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.MOVEUSP(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.STOP(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.SUBX(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.SWAP(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.TRAP(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.Disassembler.UNLK(PendleCodeMonkey.MC68000EmulatorLib.Machine.Instruction,System.Text.StringBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.OpcodeExecutionHandler.SizedValue(System.UInt32,PendleCodeMonkey.MC68000EmulatorLib.Enumerations.OpSize)~System.UInt32")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.SRecordLoader.FromHex(System.String,System.Int32,System.Int32)~System.UInt32")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.Machine.ToByteArray(System.UInt16[])~System.Byte[]")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Style issue - leave as is", Scope = "member", Target = "~M:PendleCodeMonkey.MC68000EmulatorLib.OpcodeDecoder.GetInstructionInfo(System.UInt16)~PendleCodeMonkey.MC68000EmulatorLib.InstructionInfo")]
